---
deployment:
  tasks:
    - export DEPLOYPATH=$HOME/public_html/pip
    - /bin/mkdir -p "$DEPLOYPATH"
    - /usr/bin/rsync -av --delete --exclude ".git/" --exclude "node_modules/" ./ "$DEPLOYPATH/"
